name = "ColumnFrames"
uuid = "74f2e034-c79e-429d-8ecd-190b44184071"
authors = ["Peter Deffebach <p.deffebach@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
